--Criar BD
CREATE DATABASE Exercicio_1_3

USE Exercicio_1_3

CREATE TABLE Clinica(

IdClinica INT PRIMARY KEY IDENTITY,
Nome VARCHAR(20) NOT NULL,
Endereco VARCHAR(50)NOT NULL

);

CREATE TABLE Dono(

IdDono INT PRIMARY KEY IDENTITY,
NomeDono VARCHAR(30) NOT NULL,
RG VARCHAR(10)NOT NULL

);

CREATE TABLE TipoPet(

IdTipoPet INT PRIMARY KEY IDENTITY,
NomeTipoPet VARCHAR(30)NOT NULL
);

CREATE TABLE Raca(

IdRaca INT PRIMARY KEY IDENTITY,
NomeRaca VARCHAR(30) NOT NULL

);

CREATE TABLE Veterinario(

IdVeterinario INT PRIMARY KEY IDENTITY,
IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica) NOT NULL, 
NomeVeterinario VARCHAR(30) NOT NULL,
CRMV VARCHAR(30) NOT NULL

);


CREATE TABLE Pet(

IdPet INT PRIMARY KEY IDENTITY,
IdDono INT FOREIGN KEY REFERENCES Dono(IdDono) NOT NULL,
IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet) NOT NULL,
IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca) NOT NULL,
NomePet VARCHAR(20) NOT NULL,
DataNascimento VARCHAR(10)NOT NULL
);

CREATE TABLE Atendimento(

IdAtendimento INT PRIMARY KEY IDENTITY,
IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario)NOT NULL,
IdPet INT FOREIGN KEY REFERENCES Pet(IdPet)NOT NULL,
Descricao VARCHAR(60) NOT NULL,
DataAtentimento VARCHAR(20)NOT NULL

);


