--Criar BD
CREATE DATABASE Exercicio_1_3

USE Exercicio_1_3

CREATE TABLE Clinica(

IdClinica INT PRIMARY KEY IDENTITY,
Nome VARCHAR(20) NOT NULL,
Endereco VARCHAR(50)NOT NULL

);

CREATE TABLE Dono(

IdDono INT PRIMARY KEY IDENTITY,
NomeDono VARCHAR(30) NOT NULL,
RG VARCHAR(10)NOT NULL

);

CREATE TABLE TipoPet(

IdTipoPet INT PRIMARY KEY IDENTITY,
NomeTipoPet VARCHAR(30)NOT NULL
);

CREATE TABLE Raca(

IdRaca INT PRIMARY KEY IDENTITY,
NomeRaca VARCHAR(30) NOT NULL

);

CREATE TABLE Veterinario(

IdVeterinario INT PRIMARY KEY IDENTITY,
IdClinica INT FOREIGN KEY REFERENCES Clinica(IdClinica),
NomeVeterinario VARCHAR(30),
CRMV VARCHAR(30)

);


CREATE TABLE Pet(

IdPet INT PRIMARY KEY IDENTITY,
IdDono INT FOREIGN KEY REFERENCES Dono(IdDono),
IdTipoPet INT FOREIGN KEY REFERENCES TipoPet(IdTipoPet),
IdRaca INT FOREIGN KEY REFERENCES Raca(IdRaca),
NomePet VARCHAR(20),
DataNascimento VARCHAR(10)
);

CREATE TABLE Atendimento(

IdAtendimento INT PRIMARY KEY IDENTITY,
IdVeterinario INT FOREIGN KEY REFERENCES Veterinario(IdVeterinario),
IdPet INT FOREIGN KEY REFERENCES Pet(IdPet)

);